#!/bin/bash
#!!#SECRET="${@}"
#!!#: ${SECRET:=`btsync --generate-secret`}
SECRET="AG5L54Z6AS7UPCCAXI3QSDIANMKGIZK2C"

echo "Starting btsync with secret: $SECRET"

echo "{
    \"device_name\": \"Sync Server\",
    \"listening_port\": 55555,
    \"storage_path\": \"/btsync/.sync\",
    \"pid_file\": \"/var/run/btsync/btsync.pid\",
    \"check_for_updates\": false,
    \"use_upnp\": false,
    \"download_limit\": 0,
    \"upload_limit\": 0,
/*    \"webui\" :
        {
            \"directory_root\": \"/var/www\",
            \"listen\" : \"0.0.0.0:8881\",
            \"login\" : \"admin\",
            \"password\" : \"password\"
        }
*/
    \"shared_folders\": [
        {
            \"secret\": \"$SECRET\",
            \"dir\": \"/var/www\",
            \"use_relay_server\": true,
            \"use_tracker\": true,
            \"use_dht\": false,
            \"search_lan\": true,
            \"use_sync_trash\": false
        }
    ]
}" > /btsync/btsync.conf

# btsync --config /btsync/btsync.conf --webui.listen 8880 --nodaemon
# btsync --config /btsync/btsync.conf --nodaemon
